# Dependabot config file. Enables updates for internal packages and schedules checks outside of office hours.
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
registries:
  npm-npmjs: # Define registry for private access
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_TOKEN}}

updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    # Allow version updates for dependencies in these registries
    registries:
      - npm-npmjs
    # Check the npm registry for updates on Sunday 7pm UTC / Monday 5am AEST. This should be out of
    # office hours so as to not block CI but not too long before people wake up, in case the updates
    # cause issues.
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "19:00"
