# List of Slack usernames (not GitHub) for the Cesium Concierge Slackbot to send release reminders for.
releaseSchedule:
  - gary, 1/4/2021
  - ian, 2/1/2021
  - kevin, 3/1/2021
  - hpinkos, 4/1/2021
  - mamato, 5/3/2021
  - sam.vargas, 6/1/2021
  - eli, 7/1/2021
  - sam, 8/2/2021
  - peter, 9/1/2021
  - sean, 10/1/2021
  - sam.suhag, 11/1/2021
  - eli, 12/1/2021
