/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_texturedata_free(a: number, b: number): void;
export function texturedata_data(a: number): Array;
export function texturedata_width(a: number): number;
export function texturedata_height(a: number): number;
export function texturedata_new(a: number, b: number, c: number, d: number): number;
export function generate_texture_from_attrs(a: number, b: number, c: number, d: number, e: number): Array;
export function __wbg_gsplatdata_free(a: number, b: number): void;
export function gsplatdata_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number): number;
export function gsplatdata_fromFloat32Arrays(a: number, b: number, c: number, d: number, e: number, f: number): Array;
export function gsplatdata_getPositions(a: number): number;
export function gsplatdata_getScales(a: number): number;
export function gsplatdata_getRotations(a: number): number;
export function gsplatdata_getColors(a: number): number;
export function radix_sort_simd(a: number): Array;
export function radix_sort_gaussians_attrs(a: number, b: number, c: number, d: number, e: number, f: number): Array;
export function radix_sort_gaussians_indexes(a: number, b: number, c: number, d: number): Array;
export function __wbg_gaussiansorter_free(a: number, b: number): void;
export function gaussiansorter_new(a: number): number;
export function gaussiansorter_sortGaussians(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): Array;
export function generate_splat_texture_from_attrs(a: number, b: number, c: number, d: number, e: number): Array;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __externref_table_dealloc(a: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __externref_table_alloc(): number;
export function __wbindgen_start(): void;
