blank_issues_enabled: true
contact_links:
- name: Ask a question
  url: https://community.cesium.com/c/cesiumjs/5
  about: Please use the community forum for general questions about using CesiumJS. We actively monitor it and love seeing what people are working on
