name: Ask a question
description: Please use the community forum (https://community.cesium.com/) for general questions about using Cesium.
body:
  - type: markdown
    attributes:
      value: |
        :exclamation: Please use the [community forum](https://community.cesium.com/) for asking questions about how to use Cesium and best practices. The core Cesium team actively monitors the forum and we love seeing what people are working on! :exclamation:
  - type: checkboxes
    id: verify
    attributes:
      label: Verification
      description: Confirm you will ask your question on our forums linked above
      options:
        - label: "Yes"