/*global define*/
define(['../Core/DeveloperError'
        ], function(
                DeveloperError) {
    "use strict";

    function throwInsantiationError() {
        throw new DeveloperError('This type should not be instantiated directly.');
    }

    /**
     * Defines the interface for data sources, which turn arbitrary data into a
     * {@link DynamicObjectCollection} for generic consumption. This object is an interface
     * for documentation purposes and is not intended to be instantiated directly.
     * @alias DataSource
     * @constructor
     */
    var DataSource = function() {
        throwInsantiationError();
    };

    /**
     * Gets an event that will be raised when non-temporal data changes
     * or if the return value of getIsTemporal changes.
     * @memberof DataSource
     *
     * @returns {Event} The event.
     */
    DataSource.prototype.getChangedEvent = throwInsantiationError;

    /**
     * Gets an event that will be raised if an error is encountered during processing.
     * @memberof DataSource
     *
     * @returns {Event} The event.
     */
    DataSource.prototype.getErrorEvent = throwInsantiationError;

    /**
     * Gets the top level clock associated with this data source, or undefined if no clock exists.
     * @memberof DataSource
     *
     * @returns {DynamicClock} The clock associated with this data source, or undefined if none exists.
     */
    DataSource.prototype.getClock = throwInsantiationError;

    /**
     * Gets the DynamicObjectCollection generated by this data source.
     * @memberof DataSource
     *
     * @returns {DynamicObjectCollection} The collection of objects generated by this data source.
     */
    DataSource.prototype.getDynamicObjectCollection = throwInsantiationError;

    /**
     * Gets a value indicating if the data varies with simulation time.  If the return value of
     * this function changes, the changed event will be raised.
     * @memberof DataSource
     *
     * @returns {Boolean} True if the data is varies with simulation time, false otherwise.
     */
    DataSource.prototype.getIsTemporal = throwInsantiationError;

    return DataSource;
});