/*global define*/
define(['../Core/AssociativeArray',
        '../Core/createGuid',
        '../Core/defined',
        '../Core/defineProperties',
        '../Core/Event',
        '../Core/TimeInterval',
        '../Core/Iso8601',
        '../Core/DeveloperError',
        '../Core/RuntimeError',
        './StoredView'
    ], function(
        AssociativeArray,
        createGuid,
        defined,
        defineProperties,
        Event,
        TimeInterval,
        Iso8601,
        DeveloperError,
        RuntimeError,
        StoredView) {
    "use strict";

    function fireChangedEvent(collection) {
        if (collection._suspendCount === 0) {
            var added = collection._addedObjects;
            var removed = collection._removedObjects;
            if (added.length !== 0 || removed.length !== 0) {
                collection._collectionChanged.raiseEvent(collection, added.values, removed.values);
                added.removeAll();
                removed.removeAll();
            }
        }
    }

    /**
     * An observable collection of {@link StoredView} instances where each instance has a unique id.
     * @alias StoredViewCollection
     * @constructor
     */
    var StoredViewCollection = function() {
        this._objects = new AssociativeArray();
        this._addedObjects = new AssociativeArray();
        this._removedObjects = new AssociativeArray();
        this._suspendCount = 0;
        this._collectionChanged = new Event();
        this._id = createGuid();
    };

    /**
     * Prevents {@link StoredViewCollection#collectionChanged} events from being raised
     * until a corresponding call is made to {@link StoredViewCollection#resumeEvents}, at which
     * point a single event will be raised that covers all suspended operations.
     * This allows for many items to be added and removed efficiently.
     * This function can be safely called multiple times as long as there
     * are corresponding calls to {@link StoredViewCollection#resumeEvents}.
     * @memberof StoredViewCollection
     */
    StoredViewCollection.prototype.suspendEvents = function() {
        this._suspendCount++;
    };

    /**
     * Resumes raising {@link StoredViewCollection#collectionChanged} events immediately
     * when an item is added or removed.  Any modifications made while while events were suspended
     * will be triggered as a single event when this function is called.
     * This function is reference counted and can safely be called multiple times as long as there
     * are corresponding calls to {@link StoredViewCollection#resumeEvents}.
     * @memberof StoredViewCollection
     *
     * @exception {DeveloperError} resumeEvents can not be called before suspendEvents.
     */
    StoredViewCollection.prototype.resumeEvents = function() {
        //>>includeStart('debug', pragmas.debug);
        if (this._suspendCount === 0) {
            throw new DeveloperError('resumeEvents can not be called before suspendEvents.');
        }
        //>>includeEnd('debug');

        this._suspendCount--;
        fireChangedEvent(this);
    };

    /**
     * The signature of the event generated by {@link StoredViewCollection#collectionChanged}.
     * @memberof StoredViewCollection
     * @function
     *
     * @param {StoredViewCollection} collection The collection that triggered the event.
     * @param {Array} added The array of {@link StoredView} instances that have been added to the collection.
     * @param {Array} removed The array of {@link StoredView} instances that have been removed from the collection.
     */
    StoredViewCollection.collectionChangedEventCallback = undefined;

    defineProperties(StoredViewCollection.prototype, {
        /**
         * Gets the event that is fired when objects are added or removed from the collection.
         * The generated event is a {@link StoredViewCollection.collectionChangedEventCallback}.
         * @memberof StoredViewCollection.prototype
         *
         * @type {Event}
         */
        collectionChanged : {
            get : function() {
                return this._collectionChanged;
            }
        },
        /**
         * Gets a globally unique identifier for this collection.
         * @memberof StoredViewCollection.prototype
         *
         * @type {String}
         */
        id : {
            get : function() {
                return this._id;
            }
        }
    });

    /**
     * Add an object to the collection.
     * @memberof StoredViewCollection
     *
     * @param {StoredView} storedView The object to be added.
     * @exception {DeveloperError} An object with <storedView.id> already exists in this collection.
     */
    StoredViewCollection.prototype.add = function(storedView) {
        //>>includeStart('debug', pragmas.debug);
        if (!defined(storedView)) {
            throw new DeveloperError('storedView is required.');
        }
        //>>includeEnd('debug');

        var id = storedView.id;
        var objects = this._objects;
        if (defined(objects.get(id))) {
            throw new RuntimeError('An object with id ' + id + ' already exists in this collection.');
        }

        objects.set(id, storedView);

        var removedObjects = this._removedObjects;
        if (!this._removedObjects.remove(id)) {
            this._addedObjects.set(id, storedView);
        }
        fireChangedEvent(this);
    };

    /**
     * Removes an object from the collection.
     * @memberof StoredViewCollection
     *
     * @param {StoredView} storedView The object to be added.
     * @returns {Boolean} true if the item was removed, false if it did not exist in the collection.
     */
    StoredViewCollection.prototype.remove = function(storedView) {
        //>>includeStart('debug', pragmas.debug);
        if (!defined(storedView)) {
            throw new DeveloperError('storedView is required');
        }
        //>>includeEnd('debug');

        return this.removeById(storedView.id);
    };

    /**
     * Removes an object with the provided id from the collection.
     * @memberof StoredViewCollection
     *
     * @param {Object} id The id of the object to remove.
     * @returns {Boolean} true if the item was removed, false if no item with the provided id existed in the collection.
     */
    StoredViewCollection.prototype.removeById = function(id) {
        //>>includeStart('debug', pragmas.debug);
        if (!defined(id)) {
            throw new DeveloperError('id is required.');
        }
        //>>includeEnd('debug');

        var objects = this._objects;
        var storedView = objects.get(id);
        if (!this._objects.remove(id)) {
            return false;
        }

        if (!this._addedObjects.remove(id)) {
            this._removedObjects.set(id, storedView);
        }
        fireChangedEvent(this);

        return true;
    };

    /**
     * Removes all stored views from the collection.
     * @memberof StoredViewCollection
     */
    StoredViewCollection.prototype.removeAll = function() {
        //The event should only contain items added before events were suspended
        //and the contents of the collection.
        var objects = this._objects;
        var objectsLength = objects.length;
        var array = objects.values;

        var addedObjects = this._addedObjects;
        var removed = this._removedObjects;

        for (var i = 0; i < objectsLength; i++) {
            var existingItem = array[i];
            var existingItemId = existingItem.id;
            var addedItem = addedObjects.get(existingItemId);
            if (!defined(addedItem)) {
                removed.set(existingItemId, existingItem);
            }
        }

        objects.removeAll();
        addedObjects.removeAll();
        fireChangedEvent(this);
    };

    /**
     * Gets an object with the specified id.
     * @memberof StoredViewCollection
     *
     * @param {Object} id The id of the object to retrieve.
     * @returns {StoredView} The object with the provided id or undefined if the id did not exist in the collection.
     */
    StoredViewCollection.prototype.getById = function(id) {
        //>>includeStart('debug', pragmas.debug);
        if (!defined(id)) {
            throw new DeveloperError('id is required.');
        }
        //>>includeEnd('debug');

        return this._objects.get(id);
    };

    /**
     * Gets the array of StoredView instances in the collection.
     * The array should not be modified directly.
     * @memberof StoredViewCollection
     *
     * @returns {Array} the array of StoredView instances in the collection.
     */
    StoredViewCollection.prototype.getObjects = function() {
        return this._objects.values;
    };

    return StoredViewCollection;
});
