# Default values for angular-node-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: acrarolibotnonprod.azurecr.io/cesium-standalone:1.0.3
  pullPolicy: Always

application:
  name: cesium-standalone
